service_name: travis-pro
repo_token: 8A7Vr2Dc4QEHvXWauaRtUxeNbmNWNcmP5
[![Coverage Status](https://coveralls.io/repos/github/nanfuka/ireporter-api/badge.svg?branch=162823442-user-able-get-all-redflags)](https://coveralls.io/github/nanfuka/ireporter-api?branch=162823442-user-able-get-all-redflags)